/**
 * Especificaciones técnicas de h7-phev.
 *
 * Fuente: ficha técnica oficial en PDF (public/fichas/h7-phev.pdf), transcripta y revisada contra el documento.
 * Formato: columnas = versiones comparadas en la hoja (vacío si es una sola); cada fila es [etiqueta, valor];
 * valor = texto | true (incluido) | false (no incluido) | [valor por columna] cuando difiere entre versiones.
 * Las filas sin dato o no incluidas en ninguna versión no se listan.
 *
 * Respecto de la hoja:
 *  - Los renglones de chasis y frenos que la hoja pone bajo "Exterior" se agruparon como "Chasis y conducción"; el bloque de pantallas, audio y climatización, como "Multimedia y climatización".
 *  - "Potencia de Motor" y "Par motor" se rotularon como del motor eléctrico (147 HP + 175 HP del de combustión = 322 HP combinados, como indica la hoja).
 *  - La fila "limitante de fuerza + CLT" era continuación de la anterior (cinturones con doble pretensor): se unieron. Se completó un paréntesis sin cerrar.
 */
export default {
  columnas: [],
  secciones: [
    {
      titulo: 'Dimensiones',
      filas: [
        ['Largo × ancho × alto', '4.800 × 1.950 × 1.843 mm'],
        ['Distancia entre ejes', '2.738 mm'],
      ],
    },
    {
      titulo: 'Motorización',
      filas: [
        ['Motorización', 'PHEV'],
        ['Tren motriz', '2WD'],
        ['Transmisión', '4X2 DHT-1'],
        ['Motor', '4B15M'],
        ['Capacidad de batería', '19,09 kWh'],
        ['Potencia del motor eléctrico', '147 HP'],
        ['Par del motor eléctrico', '240 Nm'],
        ['Potencia motor combustión', '175 HP'],
        ['Torque motor combustión', '300 Nm'],
        ['Potencia combinada', '322 HP'],
        ['Torque combinado', '540 Nm'],
      ],
    },
    {
      titulo: 'Chasis y conducción',
      filas: [
        ['Suspensión independiente delantera McPherson', true],
        ['Suspensión independiente trasera multibrazo', true],
        ['Dirección asistida eléctrica (EPS) + sensible a la velocidad', true],
        ['Modo de asistencia de dirección ajustable (Sport/Comfort/Light) con memoria', true],
        ['Freno de estacionamiento electrónico', true],
        ['Retención automática', true],
        ['Control de par de frenos (BTC)', true],
        ['Palanca de cambios montada en la columna', true],
        ['Frenos de disco ventilados delanteros / frenos de disco ventilados traseros', true],
        ['Carga estacionaria + frenado de confort', true],
      ],
    },
    {
      titulo: 'Exterior',
      filas: [
        ['Portaruedas de repuesto exterior', true],
        ['Neumáticos y llantas', '265/60 R18'],
        ['Portón trasero manual', true],
        ['Limpiaparabrisas delantero sin cuerpo + sensor de lluvia', true],
        ['Antena de aleta de tiburón', true],
        ['Marco de ventana negro de alto brillo', true],
        ['Techo panorámico', true],
        ['Rieles del techo', true],
        ['Descarga vehículo-carga (V2L) (solo PHEV)', true],
        ['Cristal con tinte verde', true],
        ['Ventanas eléctricas de un solo toque (4 puertas) + antipellizco', true],
        ['Cierre automático remoto de la ventana', true],
        ['Espejos laterales plegables eléctricos con intermitentes', true],
        ['Espejos plegables automáticos al bloquear', true],
        ['Retrovisores laterales calefactados', true],
        ['Lentes espejo blancas de curvatura simple', true],
        ['Parabrisas trasero calefactado', true],
        ['Cristal aislante acústico (puertas delanteras + parabrisas)', true],
        ['Faros LED frontales ajustables eléctricamente + luces traseras LED antiniebla', true],
        ['Faros automáticos + sígueme a casa', true],
        ['Luces diurnas (DRL)', true],
        ['Alerta de freno de emergencia (EBA) + luz montada alta de Stop', true],
        ['Recordatorio de luces encendidas', true],
      ],
    },
    {
      titulo: 'Interior',
      filas: [
        ['Retrovisor interior manual antirreflejo', true],
        ['Luces de mapas', true],
        ['Lámpara del compartimento de equipaje', true],
        ['Luces LED de lectura (botón) + luz de equipaje + luz ambiente', true],
        ['Volante multifunción', true],
        ['Volante de cuero ultrafibra ajustable en 4 posiciones', true],
        ['Ajuste manual del volante en 4 posiciones', true],
        ['Paleta de asistencia del pilar B', true],
        ['Manilla del cuadro de instrumentos del lado del pasajero', true],
        ['Soporte para gafas de sol superior', true],
        ['Carga inalámbrica (50 W)', true],
        ['Toma de corriente delantera de 12 V + 12 V en compartimiento de equipaje', true],
        ['Panel de instrumentos y molduras de puerta de tacto suave', true],
        ['Placas plásticas estándar de desgaste', true],
        ['Empuñaduras de asistencia aérea (excepto el conductor)', true],
        ['Reposabrazos central delantero abatible', true],
        ['Portavasos delanteros (consola)', true],
        ['Consola central refrigerada (usando aire acondicionado)', true],
        ['Espejo de tocador + iluminación de tareas (fuente de luz puntual)', true],
        ['Manilla de asistencia en el pilar A (solo pasajero)', true],
        ['Enchufe de 220 V (compatible con el extranjero) + toma de 220 V (descarga en cabina, 2,2 kW)', true],
        ['Ganchos fijos de carga', true],
        ['Cubierta tonneau del compartimento de equipaje', true],
        ['Asientos de cuero con ajuste eléctrico en 6 posiciones (conductor) + 4 en pasajero', true],
        ['Soporte lumbar eléctrico de dos vías para el conductor', true],
        ['Asientos traseros abatibles 60/40', true],
        ['Reposabrazos central trasero con portavasos', true],
        ['Reclinación manual en el respaldo trasero (2 posiciones)', true],
      ],
    },
    {
      titulo: 'Multimedia y climatización',
      filas: [
        ['Ordenador de viaje + reconocimiento de voz', true],
        ['Cuadro de instrumentos color de 12,3" con ajuste de brillo', true],
        ['Pantalla multimedia de 15,6"', true],
        ['Radio FM/AM + AV+MP5 + Bluetooth hands-free', true],
        ['Puertos USB frontales (Tipo A + C, C: 27 W / A: 10 W) + traseros (Tipo A + C, A: 10 W / C: 15 W)', true],
        ['Volumen sensible a la velocidad', true],
        ['8 altavoces: 4 tweeters + 4 woofers', true],
        ['CarPlay (inalámbrico) + Android Auto (cableado + inalámbrico)', true],
        ['Aire acondicionado automático bizona (delantero + trasero)', true],
        ['Pantalla de temperatura exterior', true],
        ['Descongelación frontal automática', true],
        ['Filtro de aire estándar', true],
      ],
    },
    {
      titulo: 'Seguridad',
      filas: [
        ['Airbags', '6'],
        ['Cinturones de seguridad frontales con doble pretensor + limitante de fuerza + CLT', true],
        ['Cinturones de seguridad de pretensor exterior traseros que limitan la fuerza + central de 3 puntos', true],
        ['Recordatorio del cinturón de seguridad (delantero y trasero)', true],
        ['Bloqueo mecánico de seguridad infantil', true],
        ['Control de tracción (TCS)', true],
        ['Intervención de movimiento por rolls (RMI)', true],
        ['Control de descenso en cuesta (HDC) + asistencia de arranque en pendiente (HHC)', true],
        ['Sistema de anulación de frenos + asistencia de frenado (BA)', true],
        ['Control de frenos en curva (CBC + IBC) + curvas inteligentes', true],
        ['Sistema de monitorización de la presión de neumáticos (TPMS)', true],
        ['Puerto USB para cámara de salpicadero', true],
        ['Sensores de aparcamiento traseros (4) + delanteros (4)', true],
        ['Cámara de 360° + vista transparente del chasis', true],
        ['Control de crucero adaptativo + asistencia de crucero (ICA)', true],
        ['Aviso de colisión frontal + AEB', true],
        ['Asistencia de seguridad para peatones/ciclistas', true],
        ['Asistencias de carril (LDW/ LKA/ LCK)', true],
        ['Asistencia de atascos (TJA)', true],
        ['Esquiva inteligente', true],
        ['AEB-intersección', true],
        ['Reconocimiento de señales de tráfico (TSR) + alerta de límite de velocidad', true],
        ['Grabadora de datos de eventos (EDR)', true],
        ['Anclajes ISOFIX para asientos infantiles', true],
        ['Sistema de respuesta al terreno - Normal/Deportivo/Eco/Nieve', true],
        ['Monitor de fatiga del conductor (basado en ángulo de dirección)', true],
        ['Encuentra mi coche: Luces + bocina', true],
        ['Inmovilizador de motor', true],
        ['Sistema de alarma antirrobo (luces + bocina) + cierre centralizado + detección de puerta entreabierta', true],
        ['Cerraduras automáticas de puertas + ventanas con detección de velocidad', true],
        ['Desbloqueo automático tras colisión', true],
        ['Reactivación automática de la cerradura de puerta', true],
        ['Protección antibloqueo', true],
        ['Entrada sin llave (puertas principales)', true],
      ],
    },
  ],
};
