/**
 * Especificaciones técnicas de poer-p500.
 *
 * Fuente: ficha técnica oficial en PDF (public/fichas/poer-p500.pdf), transcripta y revisada contra el documento.
 * Formato: columnas = versiones comparadas en la hoja (vacío si es una sola); cada fila es [etiqueta, valor];
 * valor = texto | true (incluido) | false (no incluido) | [valor por columna] cuando difiere entre versiones.
 * Las filas sin dato o no incluidas en ninguna versión no se listan.
 *
 * Respecto de la hoja:
 *  - Hoja sin texto (solo imagen): leída con OCR local y corregida a mano contra la imagen.
 *  - Se corrigieron evidentes errores de la hoja: "luces largas y largas" (por largas y cortas), "Pasador delantero" (por Pasajero delantero), "Retrovisor retrovisor".
 *  - Se agregaron las unidades que faltaban en las medidas (mm).
 */
export default {
  columnas: [],
  secciones: [
    {
      titulo: 'Motor',
      filas: [
        ['Motor', '2.0T PHEV'],
        ['Tecnología de tracción a las cuatro ruedas', '4X4 (Hi4-T)'],
        ['Transmisión', '9HAT'],
        ['Potencia máxima combinada (HP)', '402'],
        ['Torque combinado (Nm)', '750'],
        ['Potencia del motor eléctrico (HP)', '161'],
        ['Torque eléctrico (Nm)', '400'],
        ['Potencia del motor (HP)', '248'],
        ['Torque combustión (Nm)', '385'],
        ['Ángulo de aproximación', '29°'],
        ['Ángulo de salida', '26,4°'],
        ['Altura libre al suelo', '218 mm'],
        ['Profundidad de vadeo', '800 mm'],
        ['Bloqueo electrónico del diferencial en el eje trasero', true],
        ['Engranaje electrónico P', true],
        ['Suspensión independiente de doble triángulo - delantera', true],
        ['Suspensión multibrazo (cinco brazos) no independiente - trasera', true],
        ['Pinza de freno plateada', true],
        ['Intensidad ajustable de recuperación de energía de frenado', true],
        ['Aparcamiento automático', true],
      ],
    },
    {
      titulo: 'Exterior',
      filas: [
        ['Longitud', '5.440 mm'],
        ['Anchura', '1.991 mm'],
        ['Altura', '1.924 mm'],
        ['Distancia entre ejes', '3.350 mm'],
        ['Neumáticos', '265/60 R18 AT'],
        ['Retrovisores exteriores - asistencia de memoria/plegado automático al bloquear el coche/ajuste eléctrico/desempañado/ intermitente', true],
        ['Portaequipajes', true],
        ['Escalón lateral fijo eléctrico', true],
        ['Remolque + puerto de alimentación reservado para remolque + dispositivo de remolque trasero', true],
        ['Caja de carga pulverizadora', true],
        ['Bloqueo electrónico del panel trasero de la caja de carga', true],
        ['Panel trasero del maletero dividido', true],
        ['Desempañamiento de la línea directa de la luneta trasera', true],
        ['Ventanas de un toque + anti-pellizco + cierre automático de las ventanas', true],
        ['Faros LED (con el logo de Poer)', true],
        ['Faros antiniebla delanteros con luces automáticas de giro/ traseros antiniebla', true],
        ['Faros de ajuste eléctrico de altura', true],
        ['Faros automáticos', true],
        ['Luces diurnas', true],
        ['Sistema automático de conmutación de luces largas y cortas', true],
        ['Iluminación de carga', true],
        ['Sigue a casa', true],
        ['Faros combinados negros', true],
        ['Luces traseras combinadas - negras', true],
        ['Parasol + espejo de maquillaje + iluminación de maquillaje', true],
        ['Retrovisor electrónico antirreflejo', true],
      ],
    },
    {
      titulo: 'Interior',
      filas: [
        ['Pantalla de instrumentales', '12,3"'],
        ['Pantalla multimedia', '14,6"'],
        ['AV+MP5', true],
        ['USB frontal (Tipo A + Tipo C) / trasero (2 Tipo A)', true],
        ['Ordenador de conducción', true],
        ['Sistema de llamadas manos libres Bluetooth', true],
        ['Fuente de alimentación de 220 V integrada en el coche', true],
        ['Fuente de alimentación de 220 V para la caja de carga', true],
        ['Interfaz de alimentación USB para grabador de conducción', true],
        ['Carga inalámbrica delantera/ trasera', true],
        ['Reloj electrónico', true],
        ['Entrada sin llave lado conductor + copiloto', true],
        ['AVAS', true],
        ['CarPlay y Android Auto inalámbrico', true],
        ['Altavoces Infinity', '10'],
        ['Amplificador independiente', true],
        ['Función de ajuste de volumen dependiente de la velocidad', true],
        ['Zona de doble temperatura con aire acondicionado automático', true],
        ['Modo de circulación interna de un solo botón', true],
        ['Aire acondicionado: salidas de aire traseras superiores e inferiores', true],
        ['Pantalla de temperatura exterior', true],
        ['Modo de confort del aire acondicionado opcional', true],
        ['Filtro de polvo del elemento N95', true],
        ['Volante de cuero de microfibra con ajuste manual del volante en cuatro direcciones', true],
        ['Calefacción eléctrica del volante', true],
        ['Dirección multimodo/ asistida eléctrica', true],
        ['Recordatorio del volante no volviendo al centro', true],
        ['Botón mecánico multifunción del volante', true],
        ['Cambio de levas en el volante', true],
        ['Asiento de cuero genuino', true],
        ['Conductor: ajuste eléctrico de 8 posiciones + asistencia de memoria + asiento de bienvenida', true],
        ['Pasajero delantero: ajuste eléctrico de 6 posiciones', true],
        ['Asiento del conductor: soporte lumbar eléctrico ajustable en 4 posiciones', true],
        ['Calefacción de 9 velocidades/ ventilación en los asientos delanteros', true],
        ['Masaje de 8 puntos en el asiento delantero', true],
        ['Calefacción/ ventilación de 3 velocidades en la segunda fila', true],
        ['Asiento de la segunda fila: ajuste eléctrico de 2 vías', true],
        ['Reposabrazos central del asiento de la segunda fila con portavasos y caja de almacenamiento', true],
        ['Fila delantera + segunda fila reposacabezas ajustable en 2 vías', true],
        ['Luz ambiental multicolor y luz de fondo: ritmo + agua', true],
        ['Luz ambiental del salpicadero', true],
        ['Techo solar panorámico', true],
        ['Luz lateral del techo', true],
      ],
    },
    {
      titulo: 'Seguridad',
      filas: [
        ['Airbags', '6'],
        ['Cinturones delanteros: ajustables, preajustados + limitados por fuerza', true],
        ['Cinturones de seguridad en segunda fila: cinturones de seguridad limitados por la fuerza 3P*3 en ambos lados', true],
        ['ABS+EBD+TCS+RMI+ESC+IBC', true],
        ['BAS', true],
        ['EPB', true],
        ['Asistencia en subida y bajada', true],
        ['Asistencia dinámica de estabilidad direccional', true],
        ['Función de mitigación de balanceo del remolque', true],
        ['Sistema integrado de control de frenos', true],
        ['Función de desbloqueo automático tras la colisión', true],
        ['Sistema de corte de combustible en colisión', true],
        ['Grabadora de datos de accidentes EDR', true],
        ['Antirrobo de motores', true],
        ['TPMS', true],
        ['Dispositivo de fijación de asientos infantiles', true],
        ['Sistema de aparcamiento totalmente automático por fusión', true],
        ['Control de crucero adaptativo + asistente de crucero inteligente + asistencia de atascos + curvas inteligentes', true],
        ['Aviso de colisión frontal + frenado automático de emergencia + peatón + asistencia de seguridad + asistencia de seguridad en bicicleta', true],
        ['Aviso de salida de carril + mantenimiento de carril + centrado de carril + mantenimiento de carril de emergencia + esquiva inteligente', true],
        ['Recordatorio de señales de tráfico + función de alarma de exceso de velocidad + asistente de velocidad inteligente', true],
        ['Frenado de emergencia a baja velocidad', true],
        ['Asistencia de incorporación de carril', true],
        ['Aviso de apertura de puerta', true],
        ['Aviso de colisión trasera', true],
        ['Radar de marcha atrás + aviso de marcha atrás + frenado de marcha atrás', true],
        ['Sistema de advertencia de frenos de emergencia', true],
        ['Sistema de prioridad de frenos', true],
        ['Vista envolvente de 360 grados', true],
      ],
    },
  ],
};
